# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'NasaAPOD-Flux' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for NasaAPOD-Flux
  pod 'ReSwift'

  target 'NasaAPOD-FluxTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
